# Generated by Django 3.2.7 on 2021-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_types', '0001_initial'),
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='types',
            field=models.ManyToManyField(related_name='art', to='art_types.ArtType'),
        ),
    ]
